# Generated by Django 2.2.7 on 2019-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_save_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
