# Generated by Django 2.2.7 on 2019-12-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_save_app', '0002_goal_goal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('save', 'save'), ('spend', 'spend'), ('give', 'give'), ('goal', 'goal')], default='save', max_length=20),
        ),
    ]
