# Generated by Django 2.2.7 on 2019-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_save_app', '0003_auto_20191201_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
